import os
import sys
import json
import pathlib
import mimetypes
import urllib.request
import urllib.error
import ssl
import uuid
from urllib.parse import urlsplit
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer

# Create an unverified SSL context to bypass corporate proxy certificate inspection errors
ssl_context = ssl._create_unverified_context()

# The development environment may expose a dead local proxy. Supabase is
# called directly so that proxy settings cannot make the app fall back to
# LocalStorage unnecessarily.
supabase_opener = urllib.request.build_opener(
    urllib.request.ProxyHandler({}),
    urllib.request.HTTPSHandler(context=ssl_context),
)

def open_remote(request):
    return supabase_opener.open(request, timeout=10)

# Load environment variables from .env if present
def load_env():
    # Check standard root path
    env_path = pathlib.Path(__file__).parent / ".env"
    # Check Render's default secrets directory path
    secrets_path = pathlib.Path("/etc/secrets/.env")
    
    target_path = None
    if env_path.exists():
        target_path = env_path
    elif secrets_path.exists():
        target_path = secrets_path
        
    if target_path:
        print(f"Carregando credenciais do arquivo {target_path}...")
        with open(target_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" in line:
                    key, val = line.split("=", 1)
                    os.environ[key.strip()] = val.strip()

load_env()

# Generate a random token for user authentication simulation
def generate_random_token():
    return uuid.uuid4().hex

SUPABASE_URL = os.environ.get("SUPABASE_URL", "")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY", "")
PORT = int(os.environ.get("PORT", 8001))

# Request codes are generated by the backend, never by the browser.
REQUEST_CODE_COUNTER = 0

def get_next_code():
    global REQUEST_CODE_COUNTER
    REQUEST_CODE_COUNTER += 1
    return f"#{REQUEST_CODE_COUNTER:06d}"

# Credenciais padrão simuladas
USER_DEFAULT_EMAIL = os.getenv('USER_DEFAULT_EMAIL', 'user@example.com')
USER_DEFAULT_PASSWORD = os.getenv('USER_DEFAULT_PASSWORD', 'user123')
ADMIN_DEFAULT_EMAIL = os.getenv('ADMIN_DEFAULT_EMAIL', 'admin@example.com')
ADMIN_DEFAULT_PASSWORD = os.getenv('ADMIN_DEFAULT_PASSWORD', 'admin123')

class SecureBackendHandler(SimpleHTTPRequestHandler):
    def end_headers(self):
        # Prevent caching of JS/CSS during development
        request_path = urlsplit(self.path).path
        if request_path.endswith((".js", ".css", ".html")):
            self.send_header("Cache-Control", "no-cache, no-store, must-revalidate")
            self.send_header("Pragma", "no-cache")
            self.send_header("Expires", "0")
        super().end_headers()

    def do_HEAD(self):
        if self.path == "/api/cases":
            self.send_response(200)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.end_headers()
        else:
            super().do_HEAD()

    def do_GET(self):
        if self.path == "/api/cases":
            self.handle_get_cases()
        elif self.path == "/api/municipalities":
            self.handle_get_municipalities()
        else:
            # Fallback to serving static files (index.html, style.css, app.js, etc.)
            super().do_GET()

    def do_POST(self):
        # Rotas de login simuladas
        if self.path == "/api/cases":
            self.handle_post_case()
        elif self.path == "/api/municipalities":
            self.handle_post_municipality()
        elif self.path == "/api/login/user":
            self.handle_user_login()
        elif self.path == "/api/login/admin":
            self.handle_admin_login()
        else:
            self.send_error(404, "Endpoint não encontrado")

    def handle_get_cases(self):
        if not SUPABASE_URL or not SUPABASE_KEY:
            self.send_json_response(500, {"error": "Credenciais do Supabase não configuradas no servidor."})
            return

        url = f"{SUPABASE_URL}/rest/v1/cases?select=*"
        headers = {
            "apikey": SUPABASE_KEY,
            "Authorization": f"Bearer {SUPABASE_KEY}",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
        }

        req = urllib.request.Request(url, headers=headers)
        try:
            with open_remote(req) as response:
                data = json.loads(response.read().decode("utf-8"))
                self.send_json_response(200, data)
        except urllib.error.HTTPError as e:
            err_msg = e.read().decode("utf-8")
            print(f"Erro do Supabase (GET): {e.code} - {err_msg}")
            self.send_json_response(e.code, {"error": err_msg})
        except Exception as e:
            print(f"Erro interno de rede (GET): {str(e)}")
            self.send_json_response(500, {"error": str(e)})

    def handle_get_municipalities(self):
        if not SUPABASE_URL or not SUPABASE_KEY:
            self.send_json_response(500, {"error": "Credenciais do Supabase não configuradas no servidor."})
            return
        url = f"{SUPABASE_URL}/rest/v1/municipalities?select=*&order=id.desc"
        headers = {"apikey": SUPABASE_KEY, "Authorization": f"Bearer {SUPABASE_KEY}"}
        try:
            with open_remote(urllib.request.Request(url, headers=headers)) as response:
                self.send_json_response(200, json.loads(response.read().decode("utf-8")))
        except urllib.error.HTTPError as e:
            self.send_json_response(e.code, {"error": e.read().decode("utf-8")})
        except Exception as e:
            self.send_json_response(500, {"error": str(e)})

    def handle_post_case(self):
        if not SUPABASE_URL or not SUPABASE_KEY:
            self.send_json_response(500, {"error": "Credenciais do Supabase não configuradas no servidor."})
            return

        content_length = int(self.headers.get("Content-Length", 0))
        post_data = json.loads(self.rfile.read(content_length))
        records = post_data if isinstance(post_data, list) else [post_data]
        for record in records:
            record['status'] = 'pending'
            record['request_code'] = get_next_code()

        url = f"{SUPABASE_URL}/rest/v1/cases"
        headers = {
            "apikey": SUPABASE_KEY,
            "Authorization": f"Bearer {SUPABASE_KEY}",
            "Content-Type": "application/json",
            "Prefer": "return=representation"
        }

        payload = records if isinstance(post_data, list) else records[0]
        req = urllib.request.Request(url, data=json.dumps(payload).encode("utf-8"), headers=headers, method="POST")
        try:
            with open_remote(req) as response:
                data = json.loads(response.read().decode("utf-8"))
                if isinstance(data, list) and len(data) == 1:
                    data = data[0]
                self.send_json_response(201, data)
        except Exception as e:
            self.send_json_response(500, {"error": str(e)})

    def handle_post_municipality(self):
        if not SUPABASE_URL or not SUPABASE_KEY:
            self.send_json_response(500, {"error": "Credenciais do Supabase não configuradas no servidor."})
            return
        content_length = int(self.headers.get("Content-Length", 0))
        payload = json.loads(self.rfile.read(content_length))
        payload["status"] = "pending"
        url = f"{SUPABASE_URL}/rest/v1/municipalities"
        headers = {
            "apikey": SUPABASE_KEY,
            "Authorization": f"Bearer {SUPABASE_KEY}",
            "Content-Type": "application/json",
            "Prefer": "return=representation"
        }
        try:
            req = urllib.request.Request(url, data=json.dumps(payload).encode("utf-8"), headers=headers, method="POST")
            with open_remote(req) as response:
                data = json.loads(response.read().decode("utf-8"))
                self.send_json_response(201, data[0] if isinstance(data, list) and len(data) == 1 else data)
        except Exception as e:
            self.send_json_response(500, {"error": str(e)})

    def handle_approve_case(self, case_id):
        url = f"{SUPABASE_URL}/rest/v1/cases?id=eq.{case_id}"
        headers = {"apikey": SUPABASE_KEY, "Authorization": f"Bearer {SUPABASE_KEY}", "Content-Type": "application/json", "Prefer": "return=representation"}
        patch_data = json.dumps({"status": "approved"}).encode('utf-8')
        req = urllib.request.Request(url, data=patch_data, headers=headers, method='PATCH')
        try:
            with open_remote(req) as response:
                case = json.loads(response.read().decode('utf-8'))[0]
                self.send_json_response(200, case)
        except Exception as e:
            self.send_json_response(500, {"error": str(e)})

    def handle_reject_case(self, case_id):
        url = f"{SUPABASE_URL}/rest/v1/cases?id=eq.{case_id}"
        headers = {"apikey": SUPABASE_KEY, "Authorization": f"Bearer {SUPABASE_KEY}", "Content-Type": "application/json", "Prefer": "return=representation"}
        patch_data = json.dumps({"status": "rejected"}).encode('utf-8')
        req = urllib.request.Request(url, data=patch_data, headers=headers, method='PATCH')
        try:
            with open_remote(req) as response:
                case = json.loads(response.read().decode('utf-8'))[0]
                self.send_json_response(200, case)
        except Exception as e:
            self.send_json_response(500, {"error": str(e)})

    # ---------- Login Handlers ----------
    def handle_user_login(self):
        """Simulated user login. Expects JSON {"email":..., "password":...}"""
        try:
            content_length = int(self.headers.get('Content-Length', 0))
            data = json.loads(self.rfile.read(content_length))
            email = data.get('email')
            password = data.get('password')
            if email == USER_DEFAULT_EMAIL and password == USER_DEFAULT_PASSWORD:
                token = generate_random_token()
                response = {"token": token, "user": "user", "email": email}
                self.send_json_response(200, response)
            else:
                self.send_json_response(401, {"error": "Credenciais inválidas"})
        except Exception as e:
            self.send_json_response(400, {"error": str(e)})

    def handle_admin_login(self):
        """Simulated admin login. Expects JSON {"email":..., "password":...}"""
        try:
            content_length = int(self.headers.get('Content-Length', 0))
            data = json.loads(self.rfile.read(content_length))
            email = data.get('email')
            password = data.get('password')
            if email == ADMIN_DEFAULT_EMAIL and password == ADMIN_DEFAULT_PASSWORD:
                token = generate_random_token()
                response = {"token": token, "user": "admin", "email": email}
                self.send_json_response(200, response)
            else:
                self.send_json_response(401, {"error": "Credenciais inválidas"})
        except Exception as e:
            self.send_json_response(400, {"error": str(e)})

    def handle_approve_municipality(self, mun_id):
        url = f"{SUPABASE_URL}/rest/v1/municipalities?id=eq.{mun_id}"
        headers = {"apikey": SUPABASE_KEY, "Authorization": f"Bearer {SUPABASE_KEY}", "Content-Type": "application/json", "Prefer": "return=representation"}
        patch_data = json.dumps({"status": "approved"}).encode('utf-8')
        req = urllib.request.Request(url, data=patch_data, headers=headers, method='PATCH')
        try:
            with open_remote(req) as response:
                muni = json.loads(response.read().decode('utf-8'))[0]
                self.send_json_response(200, muni)
        except Exception as e:
            self.send_json_response(500, {"error": str(e)})

    def handle_reject_municipality(self, mun_id):
        url = f"{SUPABASE_URL}/rest/v1/municipalities?id=eq.{mun_id}"
        headers = {"apikey": SUPABASE_KEY, "Authorization": f"Bearer {SUPABASE_KEY}", "Content-Type": "application/json", "Prefer": "return=representation"}
        patch_data = json.dumps({"status": "rejected"}).encode('utf-8')
        req = urllib.request.Request(url, data=patch_data, headers=headers, method='PATCH')
        try:
            with open_remote(req) as response:
                muni = json.loads(response.read().decode('utf-8'))[0]
                self.send_json_response(200, muni)
        except Exception as e:
            self.send_json_response(500, {"error": str(e)})
            # Removed stray case handling block that referenced undefined 'case_id'


    def send_json_response(self, status_code, data):
        self.send_response(status_code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, PATCH, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, Authorization")
        self.end_headers()
        self.wfile.write(json.dumps(data).encode("utf-8"))

    def do_PATCH(self):
        # Simple routing for approve/reject actions
        # Expected paths:
        #   /api/cases/approve/<case_id>
        #   /api/cases/reject/<case_id>
        #   /api/municipalities/approve/<mun_id>
        #   /api/municipalities/reject/<mun_id>
        parts = self.path.strip('/').split('/')
        if len(parts) >= 4 and parts[0] == 'api':
            resource, action, identifier = parts[1], parts[2], parts[3]
            if resource == 'cases' and action == 'approve':
                self.handle_approve_case(identifier)
                return
            if resource == 'cases' and action == 'reject':
                self.handle_reject_case(identifier)
                return
            if resource == 'municipalities' and action == 'approve':
                self.handle_approve_municipality(identifier)
                return
            if resource == 'municipalities' and action == 'reject':
                self.handle_reject_municipality(identifier)
                return
        self.send_error(404, "Endpoint PATCH não encontrado")

def run():
    # Make sure we serve files from the folder where server.py is located
    server_dir = pathlib.Path(__file__).parent.resolve()
    os.chdir(server_dir)

    server_address = ("", PORT)
    httpd = ThreadingHTTPServer(server_address, SecureBackendHandler)
    print(f"============================================================")
    print(f"SERVIDOR BACKEND SEGURO RODANDO")
    print(f"Acesse: http://localhost:{PORT}/")
    print(f"Banco de dados conectado: {SUPABASE_URL}")
    print(f"============================================================")
    
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nServidor encerrado pelo usuário.")
        sys.exit(0)

if __name__ == "__main__":
    run()
